[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = default.csv
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
monitor_speed = 115200
lib_deps =
    zinggjm/GxEPD2@^1.6.3
    esp32async/ESPAsyncWebServer@^3.11.0
    esp32async/AsyncTCP@^3.3.2
    ricmoo/QRCode@^0.0.1